baseURL = "https://moshimoshi.top/"
languageCode = "zh-CN"
title = "Kisama's Blog"
theme = "loveit"

[params]
# site default theme ["auto", "light", "dark"]
# 网站默认主题 ["auto", "light", "dark"]
defaultTheme = "auto"

# Header config
# 页面头部导航栏配置
[params.header]
# desktop header mode ["fixed", "normal", "auto"]
# 桌面端导航栏模式 ["fixed", "normal", "auto"]
desktopMode = "fixed"
# mobile header mode ["fixed", "normal", "auto"]
# 移动端导航栏模式 ["fixed", "normal", "auto"]
mobileMode = "auto"
# Header title config
# 页面头部导航栏标题配置
[params.header.title]
# URL of the LOGO
# LOGO 的 URL
logo = ""
# title name
# 标题名称
name = "Kisama' Blog"
# you can add extra information before the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# whether to use typeit animation for title name
# 是否为标题显示打字机动画
typeit = false

[params.home]
# amount of RSS pages
# RSS 文章数目
rss = 10
# Home page profile
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# URL of avatar shown in home page
# 主页显示头像的 URL
avatarURL = "https://avatars.githubusercontent.com/u/62412453?v=4"
# title shown in home page (HTML format is supported)
# 主页显示的网站标题 (支持 HTML 格式)
title = "大音希声"
# subtitle shown in home page (HTML format is supported)
# 主页显示的网站副标题 (允许 HTML 格式)
subtitle = "宁愿危险而自由，不要在安逸中被奴役。"
typeit = true

[params.footer]
enable = true
# Custom content (HTML format is supported)
# 自定义内容 (支持 HTML 格式)
custom = ""
# whether to show Hugo and theme info
# 是否显示 Hugo 和主题信息
hugo = true
# whether to show copyright info
# 是否显示版权信息
copyright = true
# whether to show the author
# 是否显示作者
author = true
# site creation time
# 网站创立年份
since = 2020
# ICP info only in China (HTML format is supported)
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = '<a href="https://beian.miit.gov.cn/" target="_blank">鄂ICP备2020021065号-1</a>'
